version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.compatible
    ports:
      - "8000:8000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/vhm24
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vhm24
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
