const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log('🚀 Запуск финальной подготовки проекта VHM24 к деплою\n');

// Функция для выполнения команды и вывода результата
function runCommand(command, options = {}) {
  console.log(`Выполнение команды: ${command}`);
  try {
    const output = execSync(command, { encoding: 'utf8', ...options });
    console.log(output);
    return output;
  } catch (error) {
    console.error(`❌ Ошибка при выполнении команды: ${command}`);
    console.error(error.message);
    if (error.stdout) console.log(error.stdout.toString());
    if (error.stderr) console.error(error.stderr.toString());
    return null;
  }
}

// Функция для проверки наличия файла
function checkFileExists(filePath) {
  return fs.existsSync(filePath);
}

// Функция для создания директории, если она не существует
function ensureDirectoryExists(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
    console.log(`✅ Создана директория: ${dirPath}`);
    return true;
  }
  return false;
}

// Шаг 1: Исправление критических проблем безопасности
console.log('\n📋 Шаг 1: Исправление критических проблем безопасности');
if (checkFileExists('scripts/secure-credentials.js')) {
  runCommand('node scripts/secure-credentials.js');
} else {
  console.error('❌ Файл scripts/secure-credentials.js не найден');
}

// Шаг 2: Исправление оставшихся проблем
console.log('\n📋 Шаг 2: Исправление оставшихся проблем');
if (checkFileExists('scripts/fix-remaining-issues.js')) {
  runCommand('node scripts/fix-remaining-issues.js');
} else {
  console.error('❌ Файл scripts/fix-remaining-issues.js не найден');
}

// Шаг 3: Исправление экстренных проблем
console.log('\n📋 Шаг 3: Исправление экстренных проблем');
if (checkFileExists('scripts/emergency-fix.js')) {
  runCommand('node scripts/emergency-fix.js');
} else {
  console.error('❌ Файл scripts/emergency-fix.js не найден');
}

// Шаг 4: Создание .env.example, если его нет
console.log('\n📋 Шаг 4: Создание .env.example');
if (!checkFileExists('.env.example') && checkFileExists('.env')) {
  console.log('Создание .env.example из .env...');
  let envContent = fs.readFileSync('.env', 'utf8');
  
  // Заменяем значения переменных на примеры
  envContent = envContent
    .replace(/JWT_SECRET=.+/g, 'JWT_SECRET=your_jwt_secret_here')
    .replace(/DATABASE_URL=.+/g, 'DATABASE_URL=postgresql://user:password@localhost:5432/dbname')
    .replace(/REDIS_URL=.+/g, 'REDIS_URL=redis://localhost:6379')
    .replace(/TELEGRAM_BOT_TOKEN=.+/g, 'TELEGRAM_BOT_TOKEN=your_telegram_bot_token_here')
    .replace(/PASSWORD_\d+=.+/g, 'PASSWORD_XXX=your_password_here')
    .replace(/API_KEY_\d+=.+/g, 'API_KEY_XXX=your_api_key_here')
    .replace(/SECRET_\d+=.+/g, 'SECRET_XXX=your_secret_here');
  
  fs.writeFileSync('.env.example', envContent);
  console.log('✅ Создан .env.example из .env с удаленными чувствительными данными');
}

// Шаг 5: Создание .gitignore, если его нет
console.log('\n📋 Шаг 5: Создание .gitignore');
if (!checkFileExists('.gitignore')) {
  console.log('Создание .gitignore...');
  const gitignoreContent = `# Dependency directories
node_modules/
jspm_packages/

# Environment variables
.env
.env.*
!.env.example

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# TypeScript v1 declaration files
typings/

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env

# parcel-bundler cache (https://parceljs.org/)
.cache

# next.js build output
.next

# nuxt.js build / generate output
.nuxt
dist

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# OS specific files
.DS_Store
Thumbs.db

# IDE specific files
.idea/
.vscode/
*.swp
*.swo
`;
  
  fs.writeFileSync('.gitignore', gitignoreContent);
  console.log('✅ Создан .gitignore');
}

// Шаг 6: Создание README.md, если его нет
console.log('\n📋 Шаг 6: Создание README.md');
if (!checkFileExists('README.md')) {
  console.log('Создание README.md...');
  const readmeContent = `# VHM24 - Платформа управления вендинговыми автоматами

## Описание

VHM24 - это микросервисная платформа для управления вендинговыми автоматами. Платформа позволяет отслеживать состояние автоматов, управлять инвентарем, обрабатывать заказы и многое другое.

## Требования

- Node.js 18+
- npm 9+
- Docker и Docker Compose (опционально)
- PostgreSQL
- Redis

## Установка

1. Клонировать репозиторий:
   \`\`\`bash
   git clone https://github.com/jamshiddins/VHM24.git
   cd VHM24
   \`\`\`

2. Установить зависимости:
   \`\`\`bash
   npm install
   \`\`\`

3. Создать файл .env из .env.example:
   \`\`\`bash
   cp .env.example .env
   \`\`\`

4. Заполнить .env файл необходимыми значениями.

## Запуск

### Запуск всех сервисов

\`\`\`bash
node start-optimized.js
\`\`\`

### Запуск отдельных сервисов

\`\`\`bash
cd services/auth
npm start
\`\`\`

## Структура проекта

- \`services/\` - Микросервисы
  - \`auth/\` - Сервис аутентификации
  - \`inventory/\` - Сервис управления инвентарем
  - \`machines/\` - Сервис управления автоматами
  - \`warehouse/\` - Сервис управления складом
  - \`tasks/\` - Сервис управления задачами
  - \`data-import/\` - Сервис импорта данных
  - \`gateway/\` - API Gateway
  - \`telegram-bot/\` - Telegram бот
- \`packages/\` - Общие пакеты
  - \`database/\` - Доступ к базе данных
  - \`shared/\` - Общие утилиты
  - \`shared-types/\` - Общие типы
- \`scripts/\` - Скрипты для управления проектом
- \`docs/\` - Документация

## Деплой

### Деплой на Railway

\`\`\`bash
node scripts/deploy-to-railway.js
\`\`\`

## Тестирование

\`\`\`bash
npm test
\`\`\`

## Документация API

Документация API доступна по адресу \`/docs\` после запуска сервисов.

## Лицензия

MIT
`;
  
  fs.writeFileSync('README.md', readmeContent);
  console.log('✅ Создан README.md');
}

// Шаг 7: Запуск тестов
console.log('\n📋 Шаг 7: Запуск тестов');
if (checkFileExists('jest.config.js')) {
  runCommand('npm test');
} else {
  console.log('⚠️ Файл jest.config.js не найден, пропуск запуска тестов');
}

// Шаг 8: Проверка и обновление зависимостей
console.log('\n📋 Шаг 8: Проверка и обновление зависимостей');
runCommand('npm audit fix');

// Шаг 9: Запуск проекта для проверки
console.log('\n📋 Шаг 9: Запуск проекта для проверки');
if (checkFileExists('start-optimized.js')) {
  console.log('Для запуска проекта выполните:');
  console.log('node start-optimized.js');
} else {
  console.error('❌ Файл start-optimized.js не найден');
}

// Шаг 10: Подготовка к деплою на Railway
console.log('\n📋 Шаг 10: Подготовка к деплою на Railway');
if (checkFileExists('scripts/deploy-to-railway.js')) {
  console.log('Для деплоя на Railway выполните:');
  console.log('node scripts/deploy-to-railway.js');
} else {
  console.error('❌ Файл scripts/deploy-to-railway.js не найден');
}

console.log('\n✅ Финальная подготовка проекта VHM24 к деплою завершена!');
console.log('\n📋 Рекомендации по дальнейшему улучшению проекта:');
console.log('1. Добавить ESLint для автоматической проверки кода');
console.log('2. Настроить CI/CD pipeline для автоматического тестирования и деплоя');
console.log('3. Добавить мониторинг с использованием Prometheus и Grafana');
console.log('4. Улучшить документацию API с использованием OpenAPI/Swagger');
console.log('5. Добавить автоматическое резервное копирование базы данных');
console.log('\nПодробные рекомендации доступны в файле RECOMMENDATIONS.md');
