# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci --production=false",
  "npm install --workspaces --if-present"
]

[phases.build]
cmds = [
  "cd packages/database && npx prisma generate",
  "npm run build --if-present"
]

[start]
cmd = "node railway-start-final.js"
