[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
dependsOn = ['setup']
cmds = [
    'npm ci',
    'cd backend && npm ci',
    'cd backend && npx prisma generate'
]

[phases.build]
dependsOn = ['install']
cmds = [
    'echo "Build phase complete"'
]

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
PORT = '8000'
