[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm install", "npm install --workspaces"]

[phases.build]
cmds = ["npm run build --if-present"]

[start]
cmd = "npm run start:production"