[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["cd packages/database && npx prisma generate && cd ../.."]

[start]
cmd = "node services/gateway/src/index.js"
