[phases.setup]
nixPkgs = ["nodejs_18", "npm", "python3", "gcc"]

[phases.install]
cmds = [
  "npm ci --only=production",
  "cd backend && npm ci --only=production",
  "cd apps/telegram-bot && npm ci --only=production"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate",
  "mkdir -p logs uploads temp backups"
]

[start]
cmd = "node railway-start-production.js"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"
