[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node start-services.js --production"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

[nixpacks]
nodejs-version = "18"

[service]
internal_port = 8000
auto_rollback = true

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[[services.http_checks]]
interval = 10000
grace_period = "30s"
method = "get"
path = "/health"
protocol = "http"
timeout = 2000
tls_skip_verify = false
