[build]
builder = "nixpacks"
buildCommand = "npm ci"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

[nixpacks]
nodejs-version = "16"
