[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

[[services]]
name = "backend"
source = "."
build = "npm install && npm run build"
start = "npm run start:prod"

[env]
NODE_ENV = "production"
PORT = "3000"
