[build]
builder = "nixpacks"

[deploy]
startCommand = "npm install && npm install --workspaces && cd packages/database && npx prisma generate && cd ../../services/gateway && node src/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
