[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"
restartPolicyMaxRetries = 10

# КРИТИЧЕСКИ ВАЖНО для Railway - указывает что сервис является веб-приложением
[service.web]
type = "web"
