[build]
builder = "nixpacks"
buildCommand = "npm install && cd backend && npm install && npm run prisma:generate"

[deploy]
startCommand = "node railway-start-production.js"
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "8000"
LOG_LEVEL = "INFO"
TZ = "Asia/Tashkent"

[healthcheck]
path = "/health"
port = 8000
intervalSeconds = 30
timeoutSeconds = 10
retries = 3

[resources]
memory = "1GB"
cpu = "1vCPU"

[networking]
serviceName = "vhm24-production"
