[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate"

[deploy]
startCommand = "node scripts/deploy-to-railway.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "gateway"
port = 8000

[[services]]
name = "auth"
port = 3001

[[services]]
name = "machines"
port = 3002

[[services]]
name = "inventory"
port = 3003

[[services]]
name = "tasks"
port = 3004

[[services]]
name = "routes"
port = 3005

[[services]]
name = "warehouse"
port = 3006

[[services]]
name = "recipes"
port = 3007

[[services]]
name = "notifications"
port = 3008

[[services]]
name = "audit"
port = 3009

[[services]]
name = "monitoring"
port = 3010
