[build]
builder = "nixpacks"
buildCommand = "npm install && npm install --workspaces"

[deploy]
startCommand = "npm run start:production"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

[env]
NODE_ENV = "production"