[build]
builder = "nixpacks"
buildCommand = "npm install && npm install --workspaces"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

[env]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]
