/**;
 * Основной файл VendHub Telegram бота;
 */;
const { Telegraf } = require('telegraf')'';
const Redis = require('redis')'';
const config = require('./config/bot')'';
const { BOT_STATES } = require('./fsm/states')'';
const { createInlineKeyboard, ROLE_KEYBOARDS } = require('./keyboards')'';
const authMiddleware = require('./middleware/auth')'';
const sessionMiddleware = require('./middleware/session')'';
const loggingMiddleware = require('./middleware/logging')'';
const commonHandlers = require('./handlers/common')'';
const operatorHandlers = require('./handlers/operator')'';
const warehouseHandlers = require('./handlers/warehouse')'';
const managerHandlers = require('./handlers/manager')'';
const technicianHandlers = require('./handlers/technician')'';
const mediaHandlers = require('./handlers/media')'';
const NotificationService = require('./services/notifications')'';
const apiService = require('./services/api')'';
const userService = require('./services/users')'';
const logger = require('./utils/logger')'';
const { formatMessage } = require('./utils/formatters')'';
        logger.error('Error in start "command":''';
        { "text": '🏠 Главное меню', "callback_data": 'main_menu''';
    this.bot.command('profile''';
    this.bot.command('status''';
    this.bot.on('text''';
    this.bot.on('photo''';
    this.bot.on('location''';
    this.bot.action('main_menu''';
      if (ctx.user.role !== role && ctx.user.role !== 'ADMIN''';
        return await ctx.reply('❌ У вас нет доступа к этому разделу''';
    this.bot.action('profile''';
    this.bot.action('settings''';
      [{ "text": '⚙️ Настройки', "callback_data": 'settings''';
      [{ "text": '🏠 Главное меню', "callback_data": 'main_menu''';
    const settingsText = '⚙️ *Настройки бота*\n\n''';
      '• 🔔 Уведомления: включены\n''';
      '• 🌍 Язык: Русский\n''';
      '• 🔊 Звуки: включены\n''';
      '• 📍 Геолокация: разрешена''';
      [{ "text": '🔔 Уведомления', "callback_data": 'settings_notifications''';
      [{ "text": '🌍 Язык', "callback_data": 'settings_language''';
      [{ "text": '🔊 Звуки', "callback_data": 'settings_sounds''';
      [{ "text": '🏠 Главное меню', "callback_data": 'main_menu''';,
  "parse_mode": 'Markdown''';
        "parse_mode": 'Markdown''';
          { "text": '🏠 Главное меню', "callback_data": 'main_menu''';
      logger.error('Error getting user "status":''';
      await ctx.reply('❌ Ошибка получения статуса''';
    const message = '🔐 *Добро пожаловать в VendHub!*\n\n''';
      'Для работы с ботом необходимо пройти авторизацию.\n''';
      'Обратитесь к администратору для получения доступа.\n\n''';
      `📱 "Username": @${ctx.from.username || 'не указан''';
    await ctx.reply(message, { "parse_mode": 'Markdown''';
        if (text === '/menu' || text === 'Меню''';
          await ctx.reply('🤔 Не понимаю. Используйте кнопки меню или команду /help для справки.''';
      await ctx.reply('📸 Фото получено, но сейчас не требуется. Используйте соответствующие кнопки меню.''';
      await ctx.reply('📍 Геолокация получена, но сейчас не требуется.''';
      "OPERATOR": '📋 *Справка для оператора*\n\n''';
        '• /tasks - мои задачи\n''';
        '• /return - возврат сумок\n''';
        '• /collect - инкассация\n''';
        '• /report - отчет за смену\n''';
        '• /status - текущий статус\n''';
        '• /help - эта справка''';
      "WAREHOUSE": '📦 *Справка для склада*\n\n''';
        '• /bags - управление сумками\n''';
        '• /inventory - проверка остатков\n''';
        '• /receive - прием возвратов\n''';
        '• /wash - мойка бункеров\n''';
        '• /status - текущий статус\n''';
        '• /help - эта справка''';
      "MANAGER": '👔 *Справка для менеджера*\n\n''';
        '• /create - создать задачу\n''';
        '• /assign - назначить задачу\n''';
        '• /analytics - аналитика\n''';
        '• /reports - отчеты\n''';
        '• /alerts - настройка уведомлений\n''';
        '• /help - эта справка''';
      logger.error('Bot "error":''';
    process.on('unhandledRejection''';
      logger.error('Unhandled Rejection "at":', promise, '"reason":''';
    process.on('uncaughtException''';
      logger.error('Uncaught "Exception":''';
        await ctx.reply('❌ Произошла ошибка. Попробуйте позже или обратитесь к администратору.''';
      logger.error('Error sending error "message":''';
      const message = '🆕 *Новый пользователь*\n\n''';
        `👤 Имя: ${telegramUser.first_name ${telegramUser.last_name || '';
        `📱 "Username": @${telegramUser.username || 'не указан''';
        'Требуется предоставить доступ к системе.''';
              "parse_mode": 'Markdown''';
      logger.error('Error notifying admins about new "user":''';
        logger.info('Redis connected successfully''';
      logger.info('Notification service initialized''';
        logger.info('Bot started with polling''';
      logger.info('VendHub Manager (VHM24) Telegram Bot started successfully''';
      process.once('SIGINT''';
      process.once('SIGTERM''';
      logger.error('Failed to start "bot":''';
    logger.info('Shutting down VendHub Bot...''';
        this.bot.stop('SIGTERM''';
      logger.info('VendHub Bot stopped gracefully''';
      logger.error('Error during "shutdown":''';
}}}}}}}}}}}}})))))))))))))))))))))))))))))))))))))]]]]]]