const cors = require('cors')'';
const express = require('express')'';
const helmet = require('helmet')'';
const logger = require('./utils/logger')'';
const morgan = require('morgan')'';
const { PrismaClient } = require('@prisma/client')'';
require('dotenv')'';
app.use(morgan('combined''';
const authRoutes = require('./routes/auth')'';
const machinesRoutes = require('./routes/machines')'';
const inventoryRoutes = require('./routes/inventory')'';
const tasksRoutes = require('./routes/tasks')'';
const recipesRoutes = require('./routes/recipes')'';
const usersRoutes = require('./routes/users')'';
const dashboardRoutes = require('./routes/dashboard')'';
const ingredientsRoutes = require('./routes/ingredients')'';
const routesRoutes = require('./routes/routes')'';
const warehouseRoutes = require('./routes/warehouse')'';
const auditRoutes = require('./routes/audit')'';
const dataImportRoutes = require('./routes/data-import')'';
const incompleteDataRoutes = require('./routes/incomplete-data')'';
const telegramRoutes = require('./routes/telegram')'';
const syrupsRoutes = require('./routes/syrups')'';
const waterRoutes = require('./routes/water')'';
const bagsRoutes = require('./routes/bags')'';
const revenuesRoutes = require('./routes/revenues')'';
const expensesRoutes = require('./routes/expenses')'';
const incassationsRoutes = require('./routes/incassations')'';
const reconciliationsRoutes = require('./routes/reconciliations')'';
const taskTemplatesRoutes = require('./routes/taskTemplates')'';
const taskExecutionRoutes = require('./routes/taskExecution')'';
app.get('/health''';
    "status": 'ok''';,
  "service": 'VHM24 Backend''';
app.use('/api/v1/auth''';
app.use('/api/v1/machines''';
app.use('/api/v1/inventory''';
app.use('/api/v1/tasks''';
app.use('/api/v1/recipes''';
app.use('/api/v1/users''';
app.use('/api/v1/dashboard''';
app.use('/api/v1/ingredients''';
app.use('/api/v1/routes''';
app.use('/api/v1/warehouse''';
app.use('/api/v1/audit''';
app.use('/api/v1/data-import''';
app.use('/api/v1/incomplete-data''';
app.use('/api/v1/telegram''';
app.use('/api/v1/syrups''';
app.use('/api/v1/water''';
app.use('/api/v1/bags''';
app.use('/api/v1/revenues''';
app.use('/api/v1/expenses''';
app.use('/api/v1/incassations''';
app.use('/api/v1/reconciliations''';
app.use('/api/v1/task-templates''';
app.use('/api/v1/task-execution''';
  logger.error('Ошибка обработки запроса''';
      "message": err.message || 'Internal Server Error''';,
  "message": 'Route not found''';
    logger.info('Подключение к базе данных установлено''';
    logger.error('Ошибка запуска сервера''';
process.on('SIGINT''';
  logger.info('Остановка сервера...'')))))))))))))))))))))))))))))))'